name: Deploy

on:
    push:
        branches:
            - production-destroy

jobs:
    destroy:
        runs-on: ubuntu-latest

        environment: production

        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            TF_VAR_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            TF_VAR_ENV: ${{ vars.ENV }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup terraform
              uses: hashicorp/setup-terraform@v1

            - name: Initialise terraform
              run: |
                  terraform init

            - name: Validate terraform
              run: |
                  terraform validate

            - name: Destroy terraform
              run: |
                  terraform destroy -auto-approve
